# Generated by Django 4.2.7 on 2023-11-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_house_type_listing_home_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('House', 'House'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('Apartment', 'Apartment')], default='House', max_length=50),
        ),
    ]
