# Generated by Django 4.2.7 on 2023-12-12 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_bathrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='furniture_type',
            field=models.CharField(choices=[('Fully Furnished', 'Fully Furnished'), ('Semi Furnished', 'Semi Furnished'), ('Unfurnished', 'Unfurnished')], default='Unfurnished', max_length=50),
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_item', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
    ]
