# Generated by Django 4.2.7 on 2023-12-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_furniture_alter_furniture_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='furniture',
        ),
        migrations.AddField(
            model_name='listing',
            name='furniture',
            field=models.ManyToManyField(related_name='listings_furniture', to='listings.furniture'),
        ),
    ]
