# Generated by Django 4.2.7 on 2023-12-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_listing_furniture_listing_furniture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='furniture',
        ),
        migrations.DeleteModel(
            name='Furniture',
        ),
    ]
