# Generated by Django 4.2.7 on 2023-12-15 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('testimonial_type', models.CharField(choices=[('OWNER', 'Owner'), ('Tenant', 'Tenant'), ('Buyer', 'Buyer')], max_length=10)),
                ('creation_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
