# Generated by Django 4.2.7 on 2023-12-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_testimonial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='email_optional',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
